removed the feed button from the user popup
magshimim-next/cv-next pull request #162
Opened 2024-09-02 05:53 UTC by TheGreenOak

it looks weird but the whole popup needs to move and be more like an actual popup and less like a modal

2024-09-06 12:03 UTC, Aradon267 commented on cv_next/components/layout/navbar/popup.tsx
> +  // },
We can just delete these as we don't want them anymore

2024-09-06 12:03 UTC, Aradon267 requested changes

2024-09-06 12:03 UTC, Aradon267 commented on cv_next/components/layout/navbar/popup.tsx
> +  // },
We can just delete these as we don't want them anymore

2024-09-14 12:40 UTC, Aradon267 commented on cv_next/components/layout/navbar/popup.tsx
> +  // },
@TheGreenOak reminding you this

2024-09-14 20:51 UTC, YechiamW3 approved these changes

2024-09-16 10:58 UTC, TheGreenOak reviewed
now its removed instead of commented

2024-09-16 10:59 UTC, TheGreenOak commented
@Aradon267 why is the merging still blocked?

2024-09-19 16:23 UTC, Aradon267 approved these changes

2024-09-19 16:24 UTC, Aradon267 commented
I think that it was because  I also needed to approve this...
Can be merged now!

2024-09-20 18:02 UTC, merged